name: Test Build

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bearace_test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/bearace_test

    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bearace_test
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install Deps
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Migrate DB
        run: yarn prisma db push
      - name: Build
        run: yarn build
